export enum Color {
  PRIMARY = "#7B61FF",
  PRIMARY_LIGHT = "#917CFF",
  SECONDARY = "#80858B",
  BLACK = "#000000",
  DARK = "#242426",
  GRAPHITE = "#323537",
  ERROR = "#FF5154",
  LIGHT = "#AFB2B6",
  WHITE = "#FFFFFF",
  GREEN = "#00A340",
  YELLOW = "#F3A608",
  ORANGE = "#F45D2D",
  PRIMARY_TEXT = "var(--primary-text)",
  PRIMARY_BG = "var(--primary-bg)",
  SECONDARY_BG = "var(--secondary-bg)",
  BLOCK_BG = "var(--block-bg)",
  SELECT_BG = "var(--select-bg)",
}
